export const bookingData = [
  {
    no: 1,
    orderId: "#54637898",
    userName: "Seeam Ahmod",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "5 May 2025",
    status: "Completed",
  },
  {
    no: 2,
    orderId: "#54637899",
    userName: "Arian Rahman",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "5 May 2025",
    status: "Ongoing",
  },
  {
    no: 3,
    orderId: "#54637900",
    userName: "Nusaiba Jahan",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "5 May 2025",
    status: "Completed",
  },
  {
    no: 4,
    orderId: "#54637901",
    userName: "Rayhan Kabir",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "5 May 2025",
    status: "Ongoing",
  },
  {
    no: 5,
    orderId: "#54637902",
    userName: "Sadia Islam",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "5 May 2025",
    status: "Ongoing",
  },
  {
    no: 6,
    orderId: "#54637903",
    userName: "Tawsif Mahmud",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "5 May 2025",
    status: "Ongoing",
  },
  {
    no: 7,
    orderId: "#54637904",
    userName: "Ishrat Hossain",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "5 May 2025",
    status: "Ongoing",
  },
  {
    no: 8,
    orderId: "#54637905",
    userName: "Zahid Hasan",
    serviceName: "Interior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "6 May 2025",
    status: "Ongoing",
  },
  {
    no: 9,
    orderId: "#54637906",
    userName: "Eliza Noor",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "6 May 2025",
    status: "Completed",
  },
  {
    no: 10,
    orderId: "#54637907",
    userName: "Maruf Huda",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "6 May 2025",
    status: "Completed",
  },
  {
    no: 11,
    orderId: "#54637908",
    userName: "Priya Dey",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "7 May 2025",
    status: "Ongoing",
  },
  {
    no: 12,
    orderId: "#54637909",
    userName: "Shafayet Noman",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "7 May 2025",
    status: "Ongoing",
  },
  {
    no: 13,
    orderId: "#54637910",
    userName: "Jannatul Ferdous",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "7 May 2025",
    status: "Ongoing",
  },
  {
    no: 14,
    orderId: "#54637911",
    userName: "Kawsar Ahmed",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "8 May 2025",
    status: "Completed",
  },
  {
    no: 15,
    orderId: "#54637912",
    userName: "Farzana Aktar",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "8 May 2025",
    status: "Completed",
  },
  {
    no: 16,
    orderId: "#54637913",
    userName: "Rakin Islam",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "8 May 2025",
    status: "Completed",
  },
  {
    no: 17,
    orderId: "#54637914",
    userName: "Mousumi Jahan",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "9 May 2025",
    status: "Ongoing",
  },
  {
    no: 18,
    orderId: "#54637915",
    userName: "Raihan Mahir",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "9 May 2025",
    status: "Ongoing",
  },
  {
    no: 19,
    orderId: "#54637916",
    userName: "Afia Chowdhury",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "10 May 2025",
    status: "Completed",
  },
  {
    no: 20,
    orderId: "#54637917",
    userName: "Nahiyan Rahat",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "10 May 2025",
    status: "Ongoing",
  },
  {
    no: 21,
    orderId: "#54637908",
    userName: "Priya Dey",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "7 May 2025",
    status: "Ongoing",
  },
  {
    no: 22,
    orderId: "#54637909",
    userName: "Shafayet Noman",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "7 May 2025",
    status: "Ongoing",
  },
  {
    no: 23,
    orderId: "#54637910",
    userName: "Jannatul Ferdous",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "7 May 2025",
    status: "Ongoing",
  },
  {
    no: 24,
    orderId: "#54637911",
    userName: "Kawsar Ahmed",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "8 May 2025",
    status: "Completed",
  },
  {
    no: 25,
    orderId: "#54637912",
    userName: "Farzana Aktar",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "8 May 2025",
    status: "Completed",
  },
  {
    no: 26,
    orderId: "#54637913",
    userName: "Rakin Islam",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "8 May 2025",
    status: "Completed",
  },
  {
    no: 27,
    orderId: "#54637914",
    userName: "Mousumi Jahan",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "9 May 2025",
    status: "Ongoing",
  },
  {
    no: 28,
    orderId: "#54637915",
    userName: "Raihan Mahir",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "9 May 2025",
    status: "Ongoing",
  },
  {
    no: 29,
    orderId: "#54637916",
    userName: "Afia Chowdhury",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "10 May 2025",
    status: "Completed",
  },
  {
    no: 30,
    orderId: "#54637917",
    userName: "Nahiyan Rahat",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "10 May 2025",
    status: "Ongoing",
  },
];
