export const giftData = [
  {
    senderName: "Eleanor Pena",
    recipientName: "Eleanor Pena",
    recipientEmail: "michael.lmtc@example.com",
    eventDate: "3 May 2025",
    giftSendDate: "3 May 2025",
    amount: "$25",
    status: "Completed",
  },
  {
    senderName: "Jenny Wilson",
    recipientName: "Jenny Wilson",
    recipientEmail: "curtis.weaver@example.com",
    eventDate: "3 May 2025",
    giftSendDate: "3 May 2025",
    amount: "$50",
    status: "Failed",
  },
  {
    senderName: "Savannah Nguyen",
    recipientName: "Savannah Nguyen",
    recipientEmail: "willie.jennings@example.com",
    eventDate: "3 May 2025",
    giftSendDate: "3 May 2025",
    amount: "$100",
    status: "Completed",
  },
  {
    senderName: "Kristin Watson",
    recipientName: "Kristin Watson",
    recipientEmail: "tanya.hill@example.com",
    eventDate: "3 May 2025",
    giftSendDate: "3 May 2025",
    amount: "$120",
    status: "Failed",
  },
  {
    senderName: "John Smith",
    recipientName: "John Smith",
    recipientEmail: "john.smith@example.com",
    eventDate: "4 May 2025",
    giftSendDate: "4 May 2025",
    amount: "$30",
    status: "Completed",
  },
  {
    senderName: "Lily Adams",
    recipientName: "Lily Adams",
    recipientEmail: "lily.adams@example.com",
    eventDate: "4 May 2025",
    giftSendDate: "4 May 2025",
    amount: "$80",
    status: "Failed",
  },
  {
    senderName: "Sophia Martinez",
    recipientName: "Sophia Martinez",
    recipientEmail: "sophia.martinez@example.com",
    eventDate: "5 May 2025",
    giftSendDate: "5 May 2025",
    amount: "$70",
    status: "Completed",
  },
  {
    senderName: "Emily Clark",
    recipientName: "Emily Clark",
    recipientEmail: "emily.clark@example.com",
    eventDate: "5 May 2025",
    giftSendDate: "5 May 2025",
    amount: "$40",
    status: "Failed",
  },
  {
    senderName: "Michael Johnson",
    recipientName: "Michael Johnson",
    recipientEmail: "michael.johnson@example.com",
    eventDate: "6 May 2025",
    giftSendDate: "6 May 2025",
    amount: "$90",
    status: "Completed",
  },
  {
    senderName: "Olivia Brown",
    recipientName: "Olivia Brown",
    recipientEmail: "olivia.brown@example.com",
    eventDate: "6 May 2025",
    giftSendDate: "6 May 2025",
    amount: "$60",
    status: "Failed",
  },
  {
    senderName: "Isabella Green",
    recipientName: "Isabella Green",
    recipientEmail: "isabella.green@example.com",
    eventDate: "7 May 2025",
    giftSendDate: "7 May 2025",
    amount: "$110",
    status: "Completed",
  },
  {
    senderName: "William Taylor",
    recipientName: "William Taylor",
    recipientEmail: "william.taylor@example.com",
    eventDate: "7 May 2025",
    giftSendDate: "7 May 2025",
    amount: "$150",
    status: "Failed",
  },
  {
    senderName: "Lucas Harris",
    recipientName: "Lucas Harris",
    recipientEmail: "lucas.harris@example.com",
    eventDate: "8 May 2025",
    giftSendDate: "8 May 2025",
    amount: "$200",
    status: "Completed",
  },
  {
    senderName: "Charlotte Walker",
    recipientName: "Charlotte Walker",
    recipientEmail: "charlotte.walker@example.com",
    eventDate: "8 May 2025",
    giftSendDate: "8 May 2025",
    amount: "$75",
    status: "Failed",
  },
  {
    senderName: "Amelia Young",
    recipientName: "Amelia Young",
    recipientEmail: "amelia.young@example.com",
    eventDate: "9 May 2025",
    giftSendDate: "9 May 2025",
    amount: "$45",
    status: "Completed",
  },
  {
    senderName: "James White",
    recipientName: "James White",
    recipientEmail: "james.white@example.com",
    eventDate: "9 May 2025",
    giftSendDate: "9 May 2025",
    amount: "$50",
    status: "Failed",
  },
  {
    senderName: "Benjamin Scott",
    recipientName: "Benjamin Scott",
    recipientEmail: "benjamin.scott@example.com",
    eventDate: "10 May 2025",
    giftSendDate: "10 May 2025",
    amount: "$120",
    status: "Completed",
  },
  {
    senderName: "Henry King",
    recipientName: "Henry King",
    recipientEmail: "henry.king@example.com",
    eventDate: "10 May 2025",
    giftSendDate: "10 May 2025",
    amount: "$90",
    status: "Failed",
  },
  {
    senderName: "Jack Thomas",
    recipientName: "Jack Thomas",
    recipientEmail: "jack.thomas@example.com",
    eventDate: "11 May 2025",
    giftSendDate: "11 May 2025",
    amount: "$130",
    status: "Completed",
  },
  {
    senderName: "Grace Williams",
    recipientName: "Grace Williams",
    recipientEmail: "grace.williams@example.com",
    eventDate: "11 May 2025",
    giftSendDate: "11 May 2025",
    amount: "$110",
    status: "Failed",
  },
];
