export const giftInfoData = [
  {
    id: 1,
    recipientName: "Eleanor Pena",
    recipientEmail: "michael.mitc@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$25",
    eventDate: "3 May 2025",
    status: "Completed",
  },
  {
    id: 2,
    recipientName: "Jenny Wilson",
    recipientEmail: "curtis.weaver@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$50",
    eventDate: "3 May 2025",
    status: "Schedule",
  },
  {
    id: 3,
    recipientName: "Savannah Nguyen",
    recipientEmail: "willie.jennings@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$100",
    eventDate: "3 May 2025",
    status: "Completed",
  },
  {
    id: 4,
    recipientName: "Theresa Webb",
    recipientEmail: "btm.jennings@example.com",
    giftSendDate: "3 May 2025",
    message: "Payment issue",
    amount: "$120",
    eventDate: "3 May 2025",
    status: "Failed",
  },
  {
    id: 5,
    recipientName: "Devon Lane",
    recipientEmail: "dolores.chambers@example.com",
    giftSendDate: "3 jan 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$130",
    eventDate: "3 May 2025",
    status: "Schedule",
  },
  {
    id: 6,
    recipientName: "Esther Howard",
    recipientEmail: "cameron.tisdale@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$150",
    eventDate: "3 May 2025",
    status: "Completed",
  },
  {
    id: 7,
    recipientName: "Ralph Edwards",
    recipientEmail: "jessica.hanson@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$120",
    eventDate: "3 May 2025",
    status: "Completed",
  },
  {
    id: 8,
    recipientName: "Darlene Robertson",
    recipientEmail: "georgia.young@example.com",
    giftSendDate: "3 May 2025",
    message: "Payment issue",
    amount: "$130",
    eventDate: "3 May 2025",
    status: "Failed",
  },
  {
    id: 9,
    recipientName: "Cody Fisher",
    recipientEmail: "sara.cruz@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$50",
    eventDate: "3 May 2025",
    status: "Schedule",
  },
  {
    id: 10,
    recipientName: "Jerome Bell",
    recipientEmail: "felicia.ridd@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$130",
    eventDate: "3 May 2025",
    status: "Completed",
  },
  {
    id: 11,
    recipientName: "Marvin McKinney",
    recipientEmail: "alma.lawson@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$60",
    eventDate: "3 May 2025",
    status: "Schedule",
  },
  {
    id: 12,
    recipientName: "Guy Hawkins",
    recipientEmail: "bill.sanders@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$120",
    eventDate: "3 May 2025",
    status: "Completed",
  },
  {
    id: 13,
    recipientName: "Courtney Henry",
    recipientEmail: "courtney.henry@example.com",
    giftSendDate: "3 May 2025",
    message: "Payment issue",
    amount: "$115",
    eventDate: "3 May 2025",
    status: "Failed",
  },
  {
    id: 14,
    recipientName: "Albert Flores",
    recipientEmail: "albert.flores@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$98",
    eventDate: "3 May 2025",
    status: "Completed",
  },
  {
    id: 15,
    recipientName: "Bessie Cooper",
    recipientEmail: "bessie.cooper@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$88",
    eventDate: "3 May 2025",
    status: "Completed",
  },
  {
    id: 16,
    recipientName: "Floyd Miles",
    recipientEmail: "floyd.miles@example.com",
    giftSendDate: "3 May 2025",
    message: "Payment issue",
    amount: "$95",
    eventDate: "3 May 2025",
    status: "Failed",
  },
  {
    id: 17,
    recipientName: "Kathryn Murphy",
    recipientEmail: "kathryn.murphy@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$110",
    eventDate: "3 May 2025",
    status: "Schedule",
  },
  {
    id: 18,
    recipientName: "Jane Cooper",
    recipientEmail: "jane.cooper@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$100",
    eventDate: "3 May 2025",
    status: "Completed",
  },
  {
    id: 19,
    recipientName: "Leslie Alexander",
    recipientEmail: "leslie.alexander@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$140",
    eventDate: "3 May 2025",
    status: "Schedule",
  },
  {
    id: 20,
    recipientName: "Arlene McCoy",
    recipientEmail: "arlene.mccoy@example.com",
    giftSendDate: "3 May 2025",
    message: "Wishing you a wonderful birthday!",
    amount: "$130",
    eventDate: "3 May 2025",
    status: "Completed",
  },
];
