export const paymentHistoryData = [
  {
    paymentId: "123456",
    userName: "Eleanor Pena",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$25",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Jenny Wilson",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$50",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Savannah Nguyen",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$100",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Theresa Webb",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$120",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Devon Lane",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$120",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Esther Howard",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$120",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Ralph Edwards",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$120",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Darlene Robertson",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$120",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Cody Fisher",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$120",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Jerome Bell",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$120",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Marvin McKinney",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$120",
    status: "Completed",
  },
  {
    paymentId: "123456",
    userName: "Guy Hawkins",
    method: "Visa Card",
    date: "3 May 2025",
    amount: "$120",
    status: "Completed",
  },
];
