export const serviceRequests = [
  {
    id: "01",
    orderId: "#54637898",
    consumerName: "Paula Mora",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "Apr 12, 2025",
    avatar: null,
  },
  {
    id: "02",
    orderId: "#54637898",
    consumerName: "David Elson",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "Apr 12, 2025",
    avatar: null,
  },
  {
    id: "03",
    orderId: "#54637898",
    consumerName: "Stephanie Sharkey",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "Apr 12, 2025",
    avatar: null,
  },
  {
    id: "05",
    orderId: "#54637898",
    consumerName: "Ty Freund",
    serviceName: "Exterior Wash",
    serviceType: "Schedule Service",
    location: "New York City",
    serviceDate: "Apr 12, 2025",
    avatar: "/avatars/ty.png", // Example avatar image
  },
];
