export const userGiftData = [
  {
    id: 1,
    userName: "Eleanor Pena",
    email: "michael.mitc@example.com",
    totalGiftSend: 5,
    birthdayContact: 20,
    totalGiftAmount: "$1200",
  },
  {
    id: 2,
    userName: "Jenny Wilson",
    email: "curtis.weaver@example.com",
    totalGiftSend: 10,
    birthdayContact: 15,
    totalGiftAmount: "$2432",
  },
  {
    id: 3,
    userName: "Savannah Nguyen",
    email: "willie.jennings@example.com",
    totalGiftSend: 38,
    birthdayContact: 20,
    totalGiftAmount: "$3670",
  },
  {
    id: 4,
    userName: "Kristin Watson",
    email: "tanya.hill@example.com",
    totalGiftSend: 48,
    birthdayContact: 30,
    totalGiftAmount: "$2346",
  },
  {
    id: 5,
    userName: "Courtney Henry",
    email: "courtney.henry@example.com",
    totalGiftSend: 22,
    birthdayContact: 25,
    totalGiftAmount: "$1888",
  },
  {
    id: 6,
    userName: "Devon Lane",
    email: "devon.lane@example.com",
    totalGiftSend: 15,
    birthdayContact: 12,
    totalGiftAmount: "$1500",
  },
  {
    id: 7,
    userName: "Esther Howard",
    email: "esther.howard@example.com",
    totalGiftSend: 30,
    birthdayContact: 28,
    totalGiftAmount: "$3000",
  },
  {
    id: 8,
    userName: "Dianne Russell",
    email: "dianne.russell@example.com",
    totalGiftSend: 12,
    birthdayContact: 10,
    totalGiftAmount: "$960",
  },
  {
    id: 9,
    userName: "Wade Warren",
    email: "wade.warren@example.com",
    totalGiftSend: 19,
    birthdayContact: 16,
    totalGiftAmount: "$1800",
  },
  {
    id: 10,
    userName: "Ronald Richards",
    email: "ronald.richards@example.com",
    totalGiftSend: 40,
    birthdayContact: 35,
    totalGiftAmount: "$4230",
  },
  {
    id: 11,
    userName: "Cody Fisher",
    email: "cody.fisher@example.com",
    totalGiftSend: 9,
    birthdayContact: 8,
    totalGiftAmount: "$800",
  },
  {
    id: 12,
    userName: "Arlene McCoy",
    email: "arlene.mccoy@example.com",
    totalGiftSend: 25,
    birthdayContact: 22,
    totalGiftAmount: "$2560",
  },
  {
    id: 13,
    userName: "Jacob Jones",
    email: "jacob.jones@example.com",
    totalGiftSend: 35,
    birthdayContact: 29,
    totalGiftAmount: "$3500",
  },
  {
    id: 14,
    userName: "Guy Hawkins",
    email: "guy.hawkins@example.com",
    totalGiftSend: 14,
    birthdayContact: 12,
    totalGiftAmount: "$1250",
  },
  {
    id: 15,
    userName: "Leslie Alexander",
    email: "leslie.alex@example.com",
    totalGiftSend: 21,
    birthdayContact: 17,
    totalGiftAmount: "$2100",
  },
  {
    id: 16,
    userName: "Annette Black",
    email: "annette.black@example.com",
    totalGiftSend: 8,
    birthdayContact: 6,
    totalGiftAmount: "$600",
  },
  {
    id: 17,
    userName: "Kathryn Murphy",
    email: "kathryn.murphy@example.com",
    totalGiftSend: 27,
    birthdayContact: 23,
    totalGiftAmount: "$2750",
  },
  {
    id: 18,
    userName: "Albert Flores",
    email: "albert.flores@example.com",
    totalGiftSend: 18,
    birthdayContact: 14,
    totalGiftAmount: "$1890",
  },
  {
    id: 19,
    userName: "Bessie Cooper",
    email: "bessie.cooper@example.com",
    totalGiftSend: 29,
    birthdayContact: 26,
    totalGiftAmount: "$3020",
  },
  {
    id: 20,
    userName: "Brooklyn Simmons",
    email: "brooklyn.simmons@example.com",
    totalGiftSend: 17,
    birthdayContact: 13,
    totalGiftAmount: "$1400",
  },
];
